/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as BountyDetailsRouteImport } from './routes/bounty-details'
import { Route as BountiesRouteImport } from './routes/bounties'
import { Route as IndexRouteImport } from './routes/index'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const BountyDetailsRoute = BountyDetailsRouteImport.update({
  id: '/bounty-details',
  path: '/bounty-details',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesRoute = BountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bounties': typeof BountiesRoute
  '/bounty-details': typeof BountyDetailsRoute
  '/components': typeof ComponentsRoute
  '/design-system': typeof DesignSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bounties': typeof BountiesRoute
  '/bounty-details': typeof BountyDetailsRoute
  '/components': typeof ComponentsRoute
  '/design-system': typeof DesignSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bounties': typeof BountiesRoute
  '/bounty-details': typeof BountyDetailsRoute
  '/components': typeof ComponentsRoute
  '/design-system': typeof DesignSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bounties'
    | '/bounty-details'
    | '/components'
    | '/design-system'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bounties' | '/bounty-details' | '/components' | '/design-system'
  id:
    | '__root__'
    | '/'
    | '/bounties'
    | '/bounty-details'
    | '/components'
    | '/design-system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BountiesRoute: typeof BountiesRoute
  BountyDetailsRoute: typeof BountyDetailsRoute
  ComponentsRoute: typeof ComponentsRoute
  DesignSystemRoute: typeof DesignSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounty-details': {
      id: '/bounty-details'
      path: '/bounty-details'
      fullPath: '/bounty-details'
      preLoaderRoute: typeof BountyDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties': {
      id: '/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof BountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BountiesRoute: BountiesRoute,
  BountyDetailsRoute: BountyDetailsRoute,
  ComponentsRoute: ComponentsRoute,
  DesignSystemRoute: DesignSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
